/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "name":                 {"en": "name",                  "de": "Name",                   "ru": "Имя"},
    "description":          {"en": "description",           "de": "Beschreibung",           "ru": "Описание"},
    "Ok":                   {"en": "Ok",                    "de": "Ok",                     "ru": "Ok"},
    "Cancel":               {"en": "Cancel",                "de": "Abbrechen",              "ru": "Отмена"},
    "enabled":              {"en": "enabled",               "de": "Aktiviert",              "ru": "активно"},
    "true":                 {"en": "true",                  "de": "ja",                     "ru": "да"},
    "false":                {"en": "false",                 "de": "nein",                   "ru": "нет"},
    "Insert":               {"en": "Insert",                "de": "Einfügen",               "ru": "Вставить"},
    "copy":                 {"en": "copy",                  "de": "kopieren",               "ru": "копировать"},
    "scene":                {"en": "scene",                 "de": "szene",                  "ru": "сцена"},
    "ioBroker adapter scenes": {
        "en": "ioBroker adapter scenes",
        "de": "ioBroker adapter scenes",
        "ru": "ioBroker adapter scenes"
    },
    "delete scene":        {"en": "delete scene",         "de": "Szene löschen",            "ru": "Удалить сцену"},
    "edit scene":          {"en": "edit scene",           "de": "Szene bearbeiten",         "ru": "Редактироветь сцену"},
    "new scene":           {"en": "new scene",            "de": "Neue Szene",               "ru": "Новая сцена"},
    "edit file":            {"en": "edit file",             "de": "Datei editieren",        "ru": "Редактировать"},
    "Save":                 {"en": "Save",                  "de": "Speichern",              "ru": "Сохранить"},
    "edit":                 {"en": "edit",                  "de": "ändern",                 "ru": "редактировать"},
    "delete":               {"en": "delete",                "de": "löschen",                "ru": "удалить"},
    "ok":                   {"en": "Ok",                    "de": "Ok",                     "ru": "Ok"},
    "cancel":               {"en": "Cancel",                "de": "Abbrechen",              "ru": "отменить"},
    "Name":                 {"en": "Name",                  "de": "Name",                   "ru": "Имя"},
    "Select ID":            {"en": "Select ID",             "de": "ID Auswählen",           "ru": "Выбрать ID"},
    "Select":               {"en": "Select",                "de": "Auswählen",              "ru": "Выбрать"},
    "All":                  {"en": "All",                   "de": "Alle",                   "ru": "все"},
    "ID":                   {"en": "ID",                    "de": "ID",                     "ru": "ID"},
    "Role":                 {"en": "Role",                  "de": "Rolle",                  "ru": "Роль"},
    "Room":                 {"en": "Room",                  "de": "Raum",                   "ru": "Комната"},
    "Value":                {"en": "Value",                 "de": "Wert",                   "ru": "Значение"},
    "From":                 {"en": "From: ",                "de": "Von",                    "ru": "От"},
    "Last changed":         {"en": "Last changed",          "de": "Lätze Änderung",         "ru": "Изменён"},
    "Time stamp":           {"en": "Time stamp",            "de": "Zeitstempel",            "ru": "Время"},
    "Acknowledged":         {"en": "Acknowledged",          "de": "Bestätigt",              "ru": "Подтверждён"},
    "Processing...":        {"en": "Processing...",         "de": "Bearbeite...",           "ru": "Обработка..."},
    "Filter:":              {"en": "Filter:",               "de": "Filter:",                "ru": "Фильтр:"},
    "id":                   {"en": "ID",                    "de": "ID",                     "ru": "ID"},
    "condition":            {"en": "condition",             "de": "Bedienung",              "ru": "Условие"},
    "actual":               {"en": "actual",                "de": "Aktuell",                "ru": "Текущее"},
    "set":                  {"en": "set",                   "de": "Setzen",                 "ru": "Установить"},
    "delay":                {"en": "delay",                 "de": "Verzögerung",            "ru": "Задержка"},
    "State":                {"en": "State",                 "de": "Zustand",                "ru": "Состояния"},
    "Enabled:":             {"en": "Enabled:",              "de": "Aktiviert:",             "ru": "Активно:"},
    "Set value:":           {"en": "Set value:",            "de": "Setze Wert:",            "ru": "Установить:"},
    "Actual:":              {"en": "Actual:",               "de": "Aktuell:",               "ru": "Текущее:"},
    "Delay(ms):":           {"en": "Delay(ms):",            "de": "Verzögerung(ms):",       "ru": "Задержка(мс):"},
    "Scene":                {"en": "Scene",                 "de": "Szene",                  "ru": "Сцена"},
    "Engine:":              {"en": "Engine:",               "de": "Engine:",                "ru": "Engine:"},
    "Name:":                {"en": "Name:",                 "de": "Name:",                  "ru": "Имя:"},
    "Description:":         {"en": "Description:",          "de": "Beschreibung:",          "ru": "Описание:"},
    "Cron:":                {"en": "Cron:",                 "de": "Cron:",                  "ru": "Cron:"},
    "Trigger ID:":          {"en": "Trigger ID:",           "de": "Trigger ID:",            "ru": "ID Тринггера:"},
    "Trigger condition:":   {"en": "Trigger condition:",    "de": "Trigger-Bedienung:",     "ru": "Условие триггера:"},
    "Trigger value:":       {"en": "Trigger value:",        "de": "Trigger-Wert:",          "ru": "Значение триггера:"},
    "update scene information": {"en": "update scene information", "de": "Update",          "ru": "Обновить"},
    "collapse all":         {"en": "collapse all",          "de": "Zumachen alle",          "ru": "Свернуть все сцены"},
    "expand all":           {"en": "expand all",            "de": "Aufmachen alle",         "ru": "Развернуть все сцены"},
    "State configuration":  {"en": "State configuration",   "de": "Zustandskonfiguration",  "ru": "Настройки значения для сцены"},
    "Scene configuration":  {"en": "Scene configuration",   "de": "Szenekonfiguration",     "ru": "Настройки сцены"},
    "add states":           {"en": "add states",            "de": "Zustände hinzufügen",    "ru": "Добавить состояния"},
    "Select all":           {"en": "Select all",            "de": "Alle auswählen",         "ru": "Выбрать все видимые"},
    "Deselect all":         {"en": "Deselect all",          "de": "Alle unsekeltiern",      "ru": "Убрать выделение"},
    "Invert selection":     {"en": "Invert selection",      "de": "Selektierung invertieren", "ru": "Инвертировать выделение"},
    "Items %s":             {"en": "Items %s",              "de": "Anzahl: %s",             "ru": "%s элементов"},
    "edit state":           {"en": "edit state",            "de": "Zustand editieren",      "ru": "Редактировать состояние"},
    "delete state":         {"en": "delete state",          "de": "Zustand löschen",        "ru": "Удалить состояние"},
    "move down":            {"en": "move down",             "de": "Nach unten schieben",    "ru": "Передвинуть на 1 вниз"},
    "move up":              {"en": "move up",               "de": "Nach oben schieben",     "ru": "Передвинуть на 1 вверх"}
};
